'use client';
import {useEffect,useState} from 'react';
import './decision.css';
type Offer={id:string;company:string;role:string;city:string;monthlySalary:number;salaryMonths:number;annualBonus:number;annualHousingCost:number};
type Report={disposableAnnualIncome:number;growthScore:number;stabilityScore:number;recommendation:string};
type Detail={offer_id:string;hours:number|null;days:number|null;commute:number|null;benefits:string};
type Weights={income:number;growth:number;stability:number;balance:number};
const labels:Record<keyof Weights,string>={income:'收入',growth:'成长',stability:'稳定',balance:'生活与时间'};
const questions=[['income','balance','更高收入与更多自由时间，你更倾向哪一方？'],['growth','stability','挑战性的成长机会与成熟稳定的岗位，你更倾向哪一方？'],['income','growth','短期收入与长期技能积累，你更倾向哪一方？'],['stability','balance','工作可预期性与更短通勤，你更倾向哪一方？']] as const;
async function api<T>(path:string,method='GET',body?:unknown):Promise<T>{const token=decodeURIComponent(document.cookie.match(/(?:^|; )XSRF-TOKEN=([^;]*)/)?.[1]??'');const r=await fetch('/api/v1/decision/'+path,{method,credentials:'include',headers:{'Content-Type':'application/json',...(method==='GET'?{}:{'X-XSRF-TOKEN':token})},body:body===undefined?undefined:JSON.stringify(body)});if(!r.ok)throw new Error('保存或读取失败，请检查输入后重试');const text=await r.text();return text?JSON.parse(text):undefined as T;}
export default function DecisionWorkbench({offers,tasks,onAsk}:{offers:Offer[];tasks:Record<string,{report:Report|null}>;onAsk:(question:string)=>void}){
 const [ids,setIds]=useState<string[]>([]),[details,setDetails]=useState<Detail[]>([]),[weights,setWeights]=useState<Weights>({income:25,growth:25,stability:25,balance:25}),[saved,setSaved]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[notice,setNotice]=useState(''),[commuteIncluded,setCommuteIncluded]=useState(true),[answers,setAnswers]=useState([0,0,0,0]);
 useEffect(()=>{let alive=true;Promise.all([api<Weights>('preferences'),api<Detail[]>('details')]).then(([p,d])=>{if(alive){setWeights(p);setDetails(d);setSaved(true);setReady(true)}}).catch(e=>{if(alive)setError(e.message)});return()=>{alive=false}},[]);
 const selected=offers.filter(o=>ids.includes(o.id));
 const total=Object.values(weights).reduce((a,b)=>a+b,0);
 function detail(id:string):Detail{return details.find(d=>d.offer_id===id)??{offer_id:id,hours:null,days:null,commute:null,benefits:''}}
 function change(id:string,patch:Partial<Detail>){setDetails(old=>[...old.filter(d=>d.offer_id!==id),{...detail(id),...patch}])}
 async function saveDetail(id:string){setBusy(true);setError('');try{await api('details/'+id,'PUT',detail(id));setNotice('补充信息已保存')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function savePreferences(){setBusy(true);setError('');try{await api('preferences','PUT',weights);setSaved(true)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function applyQuiz(){const p:Weights={income:10,growth:10,stability:10,balance:10};questions.forEach(([a,b],i)=>{p[a]+=2-answers[i];p[b]+=2+answers[i]});const sum=Object.values(p).reduce((a,b)=>a+b,0);const income=Math.round(p.income*100/sum),growth=Math.round(p.growth*100/sum),stability=Math.round(p.stability*100/sum);setWeights({income,growth,stability,balance:100-income-growth-stability});setSaved(false)}
 function metrics(o:Offer){const d=detail(o.id),gross=o.monthlySalary*o.salaryMonths+o.annualBonus;const weekly=d.hours!=null&&d.days!=null&&(!commuteIncluded||d.commute!=null)?(d.hours+(commuteIncluded?2*d.commute!:0))*d.days:null;return{gross,weekly,hourly:weekly&&weekly>0?gross/(weekly*52):null}}
 function ask(kind:string){const context=selected.map(o=>({公司:o.company,岗位:o.role,城市:o.city,税前年收入:metrics(o).gross,每周占用小时:metrics(o).weekly,税前有效时薪:metrics(o).hourly,福利备注:detail(o.id).benefits.slice(0,150),成长:tasks[o.id]?.report?.growthScore??'待分析',稳定:tasks[o.id]?.report?.stabilityScore??'待分析'}));onAsk((`${kind}。请以以下对比快照为背景，结合我的简历与已保存偏好回答。工时按52周估算，${commuteIncluded?'计入':'不计入'}通勤；未知值不可猜测。当前权重${JSON.stringify(weights)}${saved?'（已保存）':'（临时未保存）'}。\n${JSON.stringify(context)}`).slice(0,1950))}
 return <section className="decision-workbench"><h2>我的 Offer 决策对比</h2><p>选择 2–3 份 Offer；补充实际工时和通勤，按你的偏好解释差异。</p>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<div className="decision-picker">{offers.map(o=><label key={o.id}><input type="checkbox" checked={ids.includes(o.id)} disabled={!ids.includes(o.id)&&ids.length>=3} onChange={e=>setIds(e.target.checked?[...ids,o.id]:ids.filter(id=>id!==o.id))}/>{o.company} · {o.role}</label>)}</div>
 <details><summary>补充信息：工时、通勤与福利</summary><p>每天实际工作时长不含休息；通勤填写单程小时。不确定的项目可以留空。</p>{selected.map(o=><fieldset key={o.id}><legend>{o.company}</legend>{([['hours','每天工作小时',0.5,24],['days','每周工作天数',0.5,7],['commute','单程通勤小时',0,6]] as const).map(([key,label,min,max])=><label key={key}>{label}<input type="number" min={min} max={max} step="0.5" value={detail(o.id)[key]??''} placeholder="待确认" onChange={e=>change(o.id,{[key]:e.target.value===''?null:Number(e.target.value)})}/></label>)}<label>福利、补贴与待确认事项<textarea value={detail(o.id).benefits} maxLength={2000} onChange={e=>change(o.id,{benefits:e.target.value})}/></label><button disabled={busy||!ready} onClick={()=>void saveDetail(o.id)}>保存补充信息</button></fieldset>)}</details>
 <details><summary>我更看重什么？{saved?'（偏好已保存）':'（尚未保存）'}</summary><p>这是决策偏好，不是心理测评。结果可修改，保存后供助手后续参考。</p>{questions.map(([a,b,q],i)=><label key={q}>{q}<span>{labels[a]} ← → {labels[b]}</span><input type="range" min={-2} max={2} value={answers[i]} onChange={e=>setAnswers(old=>old.map((v,n)=>n===i?Number(e.target.value):v))}/></label>)}<button onClick={applyQuiz}>根据回答生成权重</button><div className="decision-picker">{(Object.keys(labels) as (keyof Weights)[]).map(k=><label key={k}>{labels[k]} %<input type="number" min={0} max={100} value={weights[k]} onChange={e=>{setWeights({...weights,[k]:Number(e.target.value)});setSaved(false)}}/></label>)}</div><p>合计 {total}%</p><button disabled={!ready||busy||total!==100||Object.values(weights).some(x=>x<0||x>100)} onClick={()=>void savePreferences()}>确认并保存偏好</button></details>
 {selected.length>=2&&<><label><input type="checkbox" checked={commuteIncluded} onChange={e=>setCommuteIncluded(e.target.checked)}/>有效时薪计入往返通勤</label><div className="decision-table"><table><thead><tr><th>对比维度</th>{selected.map(o=><th key={o.id}>{o.company}<small>{o.role} · {o.city}</small></th>)}</tr></thead><tbody>{['税前年收入','年度住房支出','扣除住房后年收入（现有估算）','每周时间占用','税前有效时薪','成长 / 稳定（分析参考分）','福利与待确认事项'].map((label,i)=><tr key={label}><th>{label}</th>{selected.map(o=>{const m=metrics(o),r=tasks[o.id]?.report;return <td key={o.id}>{[`${m.gross.toLocaleString()} 元`,`${o.annualHousingCost.toLocaleString()} 元`,r?`${r.disposableAnnualIncome.toLocaleString()} 元`:'待分析',m.weekly==null?'待确认':`${m.weekly.toFixed(1)} 小时`,m.hourly==null?'待确认':`${m.hourly.toFixed(1)} 元/小时`,r?`${r.growthScore} / ${r.stabilityScore}`:'待分析',detail(o.id).benefits||'待确认'][i]}</td>})}</tr>)}</tbody></table></div><p>有效时薪 = 税前年收入 ÷（每周时间占用 × 52），未扣除节假日和休假；补贴备注未重复计入。成长和稳定分沿用现有分析，并非客观预测。</p><p>税前年收入最高：{[...selected].sort((a,b)=>metrics(b).gross-metrics(a).gross)[0].company}。工时未知时不进行时间效率判断。</p><div className="decision-picker">{['解释这几份 Offer 的主要差异','我更在意成长，请重新比较','生成向 HR 确认的问题清单'].map(q=><button key={q} onClick={()=>ask(q)}>{q}</button>)}</div></>}
 </section>
}
