'use client';

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import DecisionWorkbench from './DecisionWorkbench';
import ResumeView from './ResumeView';
import SecondaryViews from './SecondaryViews';
import './region.css';

type Offer={id:string;company:string;role:string;city:string;monthlySalary:number;salaryMonths:number;annualBonus:number;annualHousingCost:number;jobDescription?:string};
type Report={grossAnnualIncome:number;estimatedTaxAndSocialInsurance:number;disposableAnnualIncome:number;jobMatchScore:number;growthScore:number;stabilityScore:number;confidence:number;recommendation:string;strengths:string[];risks:string[];evidence:{title:string;source:string;effectiveDate:string;confidenceLevel:string}[]};
type Task={id:string;offerId:string;status:string;progress:number;report:Report|null;error:string|null;createdAt?:string;updatedAt?:string};
type Form={company:string;role:string;city:string;monthlySalary:string;salaryMonths:string;annualBonus:string;annualHousingCost:string;jobDescription:string};
type Region={code:string;province:string;city:string;baselineYear:number;sourceUrl:string};
type User={id:string;username:string;displayName:string};

const blank:Form={company:'',role:'',city:'上海',monthlySalary:'18000',salaryMonths:'13',annualBonus:'0',annualHousingCost:'48000',jobDescription:''};
const colors=['#5b5bd6','#0ea77b','#f0a23a','#db6174','#2f7ed8'];
const status:Record<string,string>={PENDING:'等待分析',CALCULATING:'计算薪税',RETRIEVING:'检索依据',REASONING:'生成建议',COMPLETED:'分析完成',FAILED:'分析失败'};
function localizedReport(report:Report|undefined,offer:Offer):Report|undefined{
  if(!report)return undefined;
  const text=[report.recommendation,...report.strengths,...report.risks].join('');
  if((text.match(/[\u3400-\u9fff]/g)?.length??0)>=10)return report;
  return {...report,recommendation:`${offer.company}的薪酬与岗位方向具备进一步比较价值，建议结合实际工作内容、团队情况和个人偏好后再做决定。`,strengths:['薪酬信息较完整，可以进行收入与生活成本比较','岗位信息可用于评估个人经历与任职要求的匹配程度'],risks:['奖金、调薪和福利的实际兑现条件需要向招聘方确认','团队稳定性、工作强度和具体职责仍需在后续沟通中核实']};
}

async function api<T>(path:string,init?:RequestInit):Promise<T>{
  const csrf=typeof document==='undefined'?'':decodeURIComponent(document.cookie.match(/(?:^|; )XSRF-TOKEN=([^;]*)/)?.[1]??'');
  const method=(init?.method??'GET').toUpperCase();
  const response=await fetch(path,{...init,credentials:'include',headers:{'Content-Type':'application/json',...(!['GET','HEAD','OPTIONS'].includes(method)&&csrf?{'X-XSRF-TOKEN':csrf}:{}),...(init?.headers||{})}});
  if(!response.ok)throw new Error((await response.text())||`请求失败（${response.status}）`);
  return response.status===204?undefined as T:response.json();
}

export default function Home(){
  const [authChecked,setAuthChecked]=useState(false),[currentUser,setCurrentUser]=useState<User|null>(null),[authMode,setAuthMode]=useState<'login'|'register'>('login');
  const [credentials,setCredentials]=useState({username:'',displayName:'',password:''}),[authError,setAuthError]=useState(''),[authBusy,setAuthBusy]=useState(false);
  const [followUp,setFollowUp]=useState('');
  const [active,setActive]=useState<'dashboard'|'offers'|'resume'|'chat'>('dashboard');
  const [offers,setOffers]=useState<Offer[]>([]),[tasks,setTasks]=useState<Record<string,Task>>({});
  const [selectedId,setSelectedId]=useState<string|null>(null);
  const [view,setView]=useState<'综合视图'|'收入视图'>('综合视图');
  const [showAdd,setShowAdd]=useState(false),[showReport,setShowReport]=useState(false);
  const [form,setForm]=useState<Form>(blank),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[offerFileBusy,setOfferFileBusy]=useState(false);
  const [regions,setRegions]=useState<Region[]>([]),[regionLoading,setRegionLoading]=useState(false);
  const [toast,setToast]=useState(''),[error,setError]=useState('');
  const flash=(text:string)=>{setToast(text);window.setTimeout(()=>setToast(''),2200)};

  const poll=useCallback(async function pollTask(taskId:string,offerId:string,count=0){
    try{const task=await api<Task>(`/api/v1/analyses/${taskId}`);setTasks(old=>({...old,[offerId]:task}));if(!['COMPLETED','FAILED'].includes(task.status)&&count<60)window.setTimeout(()=>void pollTask(taskId,offerId,count+1),1000)}
    catch(e){setError(e instanceof Error?e.message:'分析进度读取失败')}
  },[]);
  const analyze=useCallback(async(offerId:string)=>{const task=await api<Task>(`/api/v1/analyses?offerId=${offerId}`,{method:'POST'});setTasks(old=>({...old,[offerId]:task}));void poll(task.id,offerId)},[poll]);
  const load=useCallback(async()=>{try{setLoading(true);const data=await api<Offer[]>('/api/v1/offers');setOffers(data);setSelectedId(old=>old&&data.some(x=>x.id===old)?old:data[0]?.id??null);const latest=await Promise.all(data.map(o=>api<Task|null>(`/api/v1/analyses/latest?offerId=${o.id}`)));setTasks(Object.fromEntries(latest.filter(Boolean).map(t=>[t!.offerId,t!]))) }catch(e){setError(e instanceof Error?e.message:'Offer读取失败')}finally{setLoading(false)}},[]);
  useEffect(()=>{api('/api/v1/auth/csrf').then(()=>api<User>('/api/v1/auth/me')).then(setCurrentUser).catch(()=>setCurrentUser(null)).finally(()=>setAuthChecked(true))},[]);
  useEffect(()=>{if(!currentUser)return;const original=window.fetch.bind(window);window.fetch=(input,init={})=>{const csrf=decodeURIComponent(document.cookie.match(/(?:^|; )XSRF-TOKEN=([^;]*)/)?.[1]??'');const method=(init.method??'GET').toUpperCase();return original(input,{...init,credentials:'include',headers:{...(!['GET','HEAD','OPTIONS'].includes(method)&&csrf?{'X-XSRF-TOKEN':csrf}:{}),...(init.headers||{})}})};return()=>{window.fetch=original}},[currentUser]);
  useEffect(()=>{if(!currentUser)return;const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load,currentUser]);
  useEffect(()=>{if(!showAdd)return;const timer=window.setTimeout(()=>{setRegionLoading(true);api<Region[]>(`/api/v1/regions?q=${encodeURIComponent(form.city)}&limit=30`).then(setRegions).catch(()=>setRegions([])).finally(()=>setRegionLoading(false))},220);return()=>window.clearTimeout(timer)},[form.city,showAdd]);

  const rows=useMemo(()=>offers.map((o,i)=>{const task=tasks[o.id],r=localizedReport(task?.report??undefined,o),gross=r?.grossAnnualIncome??o.monthlySalary*o.salaryMonths+o.annualBonus,cash=r?.disposableAnnualIncome??Math.max(0,gross*.75-o.annualHousingCost);return{...o,task,report:r,color:colors[i%colors.length],total:gross/10000,cash:cash/10000,match:r?.jobMatchScore??0,growth:r?.growthScore??0,stability:r?.stabilityScore??0}}),[offers,tasks]);
  const selected=rows.find(x=>x.id===selectedId)??rows[0]??null,recommended=rows.find(x=>x.report)??null;

  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const body={company:form.company.trim(),role:form.role.trim(),city:form.city,monthlySalary:+form.monthlySalary,salaryMonths:+form.salaryMonths,annualBonus:+form.annualBonus,annualHousingCost:+form.annualHousingCost,jobDescription:form.jobDescription.trim()};const created=await api<Offer>('/api/v1/offers',{method:'POST',body:JSON.stringify(body)});setOffers(old=>[...old,created]);setSelectedId(created.id);setForm(blank);setShowAdd(false);await analyze(created.id);flash('Offer 已保存，正在生成分析')}catch(e){setError(e instanceof Error?e.message:'提交失败')}finally{setBusy(false)}}
  async function parseOfferFile(file?:File){if(!file)return;setOfferFileBusy(true);setError('');try{const body=new FormData();body.append('file',file);const response=await fetch('/api/v1/offers/file-preview',{method:'POST',body});if(!response.ok)throw new Error(await response.text());const parsed=await response.json() as {company?:string;role?:string;city?:string;content?:string;filename:string};setForm(old=>({...old,company:parsed.company||old.company,role:parsed.role||old.role,city:parsed.city||old.city,jobDescription:parsed.content||old.jobDescription}));setShowAdd(true);flash(`已识别 ${parsed.filename}，请确认自动填写的字段`)}catch(e){setError(e instanceof Error?e.message:'Offer 文件识别失败')}finally{setOfferFileBusy(false)}}
  async function remove(id:string){if(!confirm('确定删除这个 Offer 吗？数据库记录也会被删除。'))return;try{await api<void>(`/api/v1/offers/${id}`,{method:'DELETE'});setOffers(old=>old.filter(x=>x.id!==id));setTasks(old=>{const next={...old};delete next[id];return next});setSelectedId(null);flash('Offer 已从数据库删除')}catch(e){setError(e instanceof Error?e.message:'删除失败')}}
  async function seed(){setBusy(true);const examples=[{company:'星云科技',role:'Java 后端工程师',city:'北京',monthlySalary:22000,salaryMonths:14,annualBonus:30000,annualHousingCost:72000,jobDescription:'Java、Spring Boot、高并发订单系统'},{company:'云栖网络',role:'AI 全栈工程师',city:'杭州',monthlySalary:21000,salaryMonths:13,annualBonus:25000,annualHousingCost:48000,jobDescription:'智能应用、React、Java 全栈开发'},{company:'深海数据',role:'平台研发工程师',city:'深圳',monthlySalary:24000,salaryMonths:14,annualBonus:35000,annualHousingCost:66000,jobDescription:'Java、微服务治理、数据平台建设'}];try{const made:Offer[]=[];for(const item of examples)made.push(await api<Offer>('/api/v1/offers',{method:'POST',body:JSON.stringify(item)}));setOffers(old=>[...old,...made]);setSelectedId(made[0].id);for(const item of made)await analyze(item.id);flash('3条示例已添加')}catch(e){setError(e instanceof Error?e.message:'导入失败')}finally{setBusy(false)}}

  async function authenticate(e:FormEvent){e.preventDefault();setAuthBusy(true);setAuthError('');try{await api('/api/v1/auth/csrf');const user=await api<User>(`/api/v1/auth/${authMode}`,{method:'POST',body:JSON.stringify(credentials)});localStorage.removeItem('offerpilot.conversationId');setCurrentUser(user)}catch(e){setAuthError(e instanceof Error?e.message:'认证失败')}finally{setAuthBusy(false)}}
  async function logout(){try{await api<void>('/api/v1/auth/logout',{method:'POST'})}finally{localStorage.removeItem('offerpilot.conversationId');setCurrentUser(null);setFollowUp('');setOffers([]);setTasks({});setCredentials({username:'',displayName:'',password:''});void api('/api/v1/auth/csrf')}}
  if(!authChecked)return <main className="auth-page"><div className="loader"/></main>;
  if(!currentUser)return <main className="auth-page"><form className="auth-card" onSubmit={authenticate}><div className="brand"><span className="brand-mark">O</span><span>OfferPilot</span></div><span className="eyebrow">SECURE DECISION WORKSPACE</span><h1>{authMode==='login'?'登录账号':'注册账号'}</h1><p>{authMode==='login'?'登录后读取属于你的长期记忆。':'密码使用 BCrypt 哈希保存，不存储明文。'}</p><label>用户名<input required minLength={3} value={credentials.username} onChange={e=>setCredentials({...credentials,username:e.target.value})} placeholder="3-30位字母、数字或下划线"/></label>{authMode==='register'&&<label>显示名称<input required value={credentials.displayName} onChange={e=>setCredentials({...credentials,displayName:e.target.value})} placeholder="例如：陈同学"/></label>}<label>密码<input required minLength={8} type="password" value={credentials.password} onChange={e=>setCredentials({...credentials,password:e.target.value})} placeholder="至少8位"/></label>{authError&&<div className="auth-error">{authError}</div>}<button className="auth-submit" disabled={authBusy}>{authBusy?'请稍候…':authMode==='login'?'登录':'注册并登录'}</button><button type="button" className="auth-switch" onClick={()=>{setAuthMode(authMode==='login'?'register':'login');setAuthError('')}}>{authMode==='login'?'没有账号？立即注册':'已有账号？返回登录'}</button></form></main>;
  return <main className="app-shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">O</span><span>OfferPilot</span></div><nav><button onClick={()=>setActive('dashboard')} className={`nav-item ${active==='dashboard'?'active':''}`}><span>⌁</span> 决策工作台</button><button onClick={()=>setActive('offers')} className={`nav-item ${active==='offers'?'active':''}`}><span>▤</span> 我的 Offer <b>{offers.length}</b></button><button onClick={()=>setActive('resume')} className={`nav-item ${active==='resume'?'active':''}`}><span>▦</span> 我的简历</button><button onClick={()=>setActive('chat')} className={`nav-item ${active==='chat'?'active':''}`}><span>✦</span> 顾问问答</button></nav><div className="backend-state"><i/> 智能顾问 · 服务正常<small>资料核验 / 决策分析 / 个性化建议</small></div><div className="side-foot"><div className="avatar">{currentUser.displayName.slice(0,1)}</div><div><strong>{currentUser.displayName}</strong><small>@{currentUser.username}</small></div><button onClick={logout}>退出</button></div></aside>
    <section className="workspace">
      {active==='resume'?<ResumeView key={currentUser.id}/>:active!=='dashboard'?<SecondaryViews initialQuestion={followUp} view={active} offers={offers} onOpenOffer={id=>{setSelectedId(id);setActive('dashboard')}}/>:<>
      <header className="topbar"><div><p>你好，{currentUser.displayName}</p><h1>你的秋招决策工作台</h1></div><div className="top-actions"><button className="ghost" onClick={()=>{navigator.clipboard?.writeText(location.href);flash('报告链接已复制')}}>分享报告</button><label className={`offer-upload ${offerFileBusy?'disabled':''}`}>{offerFileBusy?'识别中…':'⇧ 上传 Offer'}<input type="file" accept=".pdf,.docx,.txt,.md,.markdown,.csv" disabled={offerFileBusy} onChange={e=>void parseOfferFile(e.target.files?.[0])}/></label><button className="primary" onClick={()=>setShowAdd(true)}>＋ 添加 Offer</button></div></header>
      {error&&<div className="error-banner"><span>!</span><b>服务请求失败</b><p>{error}</p><button onClick={()=>setError('')}>关闭</button></div>}
      <div className="insight-banner"><div className="ai-orb">✦</div><div><span>决策摘要</span><h2>{recommended?`${recommended.company} 值得优先关注`:'添加 Offer 后生成个性化分析'}</h2><p>{recommended?.report?.recommendation??'结合薪酬、岗位匹配、城市成本和你的个人偏好，整理清晰的决策依据。'}</p></div><button disabled={!recommended} onClick={()=>{setSelectedId(recommended?.id??null);setShowReport(true)}}>查看完整依据 <span>→</span></button></div>
      <div className="section-heading"><div><h2>Offer 横向对比</h2><p>核心信息一览 · 金额单位：万元/年</p></div><div className="segmented">{(['综合视图','收入视图'] as const).map(x=><button key={x} onClick={()=>setView(x)} className={view===x?'on':''}>{x}</button>)}</div></div>
      {loading?<div className="empty-state"><div className="loader"/><h3>正在加载 Offer</h3></div>:offers.length===0?<div className="empty-state"><span>◎</span><h3>还没有 Offer</h3><p>添加自己的 Offer，或先用演示数据体验完整功能。</p><div><button onClick={()=>setShowAdd(true)}>添加 Offer</button><button className="secondary" disabled={busy} onClick={seed}>{busy?'正在添加…':'使用演示数据'}</button></div></div>:<div className="offer-grid">{rows.map(o=><article key={o.id} onClick={()=>setSelectedId(o.id)} className={`offer-card ${selectedId===o.id?'selected':''}`}><div className="offer-top"><span className="company-logo" style={{background:o.color}}>{o.company[0]}</span><div><h3>{o.company}</h3><p>{o.role} · {o.city}</p></div>{recommended?.id===o.id&&<em>重点关注</em>}</div><div className="salary"><strong>{o.total.toFixed(1)}</strong><span>万<br/>预计总包</span></div><div className="metric-row"><span>可支配收入 <b>{o.report?`${o.cash.toFixed(1)} 万`:'分析后可见'}</b></span><span>{view==='综合视图'?'岗位匹配':'住房支出'} <b>{view==='综合视图'?(o.report?`${o.match}%`:'—'):`${(o.annualHousingCost/10000).toFixed(1)} 万`}</b></span></div><div className="progress"><i style={{width:`${o.task?.progress??0}%`,background:o.color}}/></div><div className={`task-state ${o.task?.status==='FAILED'?'failed':''}`}><span>{status[o.task?.status??'']??'尚未分析'}</span><b>{o.task?.progress??0}%</b></div><div className="card-actions"><button onClick={e=>{e.stopPropagation();void analyze(o.id)}}>重新分析</button><button onClick={e=>{e.stopPropagation();void remove(o.id)}}>删除</button></div></article>)}</div>}
      <DecisionWorkbench key={currentUser.id} offers={offers} tasks={tasks} onAsk={q=>{setFollowUp(q);setActive('chat')}}/>
      </>}
    </section>
    {showAdd&&<div className="modal-backdrop" onClick={()=>!busy&&setShowAdd(false)}><form className="modal" onSubmit={submit} onClick={e=>e.stopPropagation()}><button type="button" className="close" onClick={()=>setShowAdd(false)}>×</button><span className="eyebrow">新增求职机会</span><h2>添加一个 Offer</h2><p>填写核心信息后，系统会自动生成薪酬与岗位分析。</p><fieldset><legend>1 · 基本信息</legend><label>公司与岗位<div className="field-row"><input required value={form.company} onChange={e=>setForm({...form,company:e.target.value})} placeholder="公司名称"/><input required value={form.role} onChange={e=>setForm({...form,role:e.target.value})} placeholder="岗位名称"/></div></label><label>工作城市<div className="region-picker"><input required autoComplete="off" value={form.city} onChange={e=>setForm({...form,city:e.target.value})} placeholder="输入城市、自治州或地区名称"/>{regionLoading&&<i>查询中…</i>}{form.city&&regions.length>0&&<div>{regions.map(r=><button type="button" key={r.code} onClick={()=>{setForm({...form,city:r.city});setRegions([])}}><b>{r.city}</b><span>{r.province} · 区划基准 {r.baselineYear}</span></button>)}</div>}</div></label></fieldset><fieldset><legend>2 · 薪酬与住房</legend><div className="field-row"><label>月薪（元）<input required min="1" type="number" value={form.monthlySalary} onChange={e=>setForm({...form,monthlySalary:e.target.value})}/></label><label>薪资月数<input required min="12" max="24" step="0.5" type="number" value={form.salaryMonths} onChange={e=>setForm({...form,salaryMonths:e.target.value})}/></label></div><div className="field-row"><label>年度奖金（元）<input required min="0" type="number" value={form.annualBonus} onChange={e=>setForm({...form,annualBonus:e.target.value})}/></label><label>年度住房支出（元）<input required min="0" type="number" value={form.annualHousingCost} onChange={e=>setForm({...form,annualHousingCost:e.target.value})}/></label></div></fieldset><details><summary>3 · 岗位说明（可选）</summary><label>Offer / JD内容<textarea value={form.jobDescription} onChange={e=>setForm({...form,jobDescription:e.target.value})} placeholder="粘贴岗位职责和任职要求…"/></label></details><p>工时、通勤与福利可在保存后的“决策对比”中补充，未知信息可留空。</p><button disabled={busy} className="modal-primary">{busy?'正在保存…':'保存并开始分析 →'}</button></form></div>}
    {showReport&&selected?.report&&<div className="modal-backdrop" onClick={()=>setShowReport(false)}><section className="modal report" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setShowReport(false)}>×</button><span className="eyebrow">决策分析报告</span><h2>{selected.company} 分析报告</h2><div className="report-score"><strong>{selected.match}</strong><span>岗位匹配参考分<br/><b>分析置信度 {selected.report.confidence}%</b></span></div><h3>综合建议</h3><p className="report-copy">{selected.report.recommendation}</p><h3>优势与风险</h3><ul>{selected.report.strengths.map(x=><li key={`strength-${x}`}><b>优势：</b>{x}</li>)}{selected.report.risks.map(x=><li key={`risk-${x}`}><b>风险：</b>{x}</li>)}</ul><button className="modal-primary" onClick={()=>setShowReport(false)}>我知道了</button></section></div>}
    {toast&&<div className="toast">✓ {toast}</div>}
  </main>
}
