'use client';

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import DecisionWorkbench from './DecisionWorkbench';
import ResumeView from './ResumeView';
import SecondaryViews from './SecondaryViews';
import './region.css';

type Offer={id:string;company:string;role:string;city:string;monthlySalary:number;salaryMonths:number;annualBonus:number;annualHousingCost:number;jobDescription?:string};
type Report={grossAnnualIncome:number;estimatedTaxAndSocialInsurance:number;disposableAnnualIncome:number;jobMatchScore:number;growthScore:number;stabilityScore:number;confidence:number;recommendation:string;strengths:string[];risks:string[];evidence:{title:string;source:string;effectiveDate:string;confidenceLevel:string}[]};
type Task={id:string;offerId:string;status:string;progress:number;report:Report|null;error:string|null;createdAt?:string;updatedAt?:string};
type Form={company:string;role:string;city:string;monthlySalary:string;salaryMonths:string;annualBonus:string;annualHousingCost:string;jobDescription:string};
type Region={code:string;province:string;city:string;baselineYear:number;sourceUrl:string};
type User={id:string;username:string;displayName:string};

const blank:Form={company:'',role:'',city:'上海',monthlySalary:'18000',salaryMonths:'13',annualBonus:'0',annualHousingCost:'48000',jobDescription:''};
const colors=['#5b5bd6','#0ea77b','#f0a23a','#db6174','#2f7ed8'];
const status:Record<string,string>={PENDING:'等待分析',CALCULATING:'计算薪税',RETRIEVING:'检索依据',REASONING:'生成建议',COMPLETED:'分析完成',FAILED:'分析失败'};

async function api<T>(path:string,init?:RequestInit):Promise<T>{
  const csrf=typeof document==='undefined'?'':decodeURIComponent(document.cookie.match(/(?:^|; )XSRF-TOKEN=([^;]*)/)?.[1]??'');
  const method=(init?.method??'GET').toUpperCase();
  const response=await fetch(path,{...init,credentials:'include',headers:{'Content-Type':'application/json',...(!['GET','HEAD','OPTIONS'].includes(method)&&csrf?{'X-XSRF-TOKEN':csrf}:{}),...(init?.headers||{})}});
  if(!response.ok)throw new Error((await response.text())||`请求失败（${response.status}）`);
  return response.status===204?undefined as T:response.json();
}

export default function Home(){
  const [authChecked,setAuthChecked]=useState(false),[currentUser,setCurrentUser]=useState<User|null>(null),[authMode,setAuthMode]=useState<'login'|'register'>('login');
  const [credentials,setCredentials]=useState({username:'',displayName:'',password:''}),[authError,setAuthError]=useState(''),[authBusy,setAuthBusy]=useState(false);
  const [followUp,setFollowUp]=useState('');
  const [active,setActive]=useState<'dashboard'|'offers'|'history'|'resume'|'chat'>('dashboard');
  const [offers,setOffers]=useState<Offer[]>([]),[tasks,setTasks]=useState<Record<string,Task>>({});
  const [income,setIncome]=useState(40),[growth,setGrowth]=useState(35),[selectedId,setSelectedId]=useState<string|null>(null);
  const [view,setView]=useState<'综合视图'|'收入视图'>('综合视图'),[scenario,setScenario]=useState('均衡决策');
  const [showAdd,setShowAdd]=useState(false),[showAgent,setShowAgent]=useState(false),[showReport,setShowReport]=useState(false);
  const [form,setForm]=useState<Form>(blank),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[offerFileBusy,setOfferFileBusy]=useState(false);
  const [regions,setRegions]=useState<Region[]>([]),[regionLoading,setRegionLoading]=useState(false);
  const [toast,setToast]=useState(''),[error,setError]=useState('');
  const flash=(text:string)=>{setToast(text);window.setTimeout(()=>setToast(''),2200)};

  const poll=useCallback(async function pollTask(taskId:string,offerId:string,count=0){
    try{const task=await api<Task>(`/api/v1/analyses/${taskId}`);setTasks(old=>({...old,[offerId]:task}));if(!['COMPLETED','FAILED'].includes(task.status)&&count<60)window.setTimeout(()=>void pollTask(taskId,offerId,count+1),1000)}
    catch(e){setError(e instanceof Error?e.message:'分析进度读取失败')}
  },[]);
  const analyze=useCallback(async(offerId:string)=>{const task=await api<Task>(`/api/v1/analyses?offerId=${offerId}`,{method:'POST'});setTasks(old=>({...old,[offerId]:task}));void poll(task.id,offerId)},[poll]);
  const load=useCallback(async()=>{try{setLoading(true);const data=await api<Offer[]>('/api/v1/offers');setOffers(data);setSelectedId(old=>old&&data.some(x=>x.id===old)?old:data[0]?.id??null);const latest=await Promise.all(data.map(o=>api<Task|null>(`/api/v1/analyses/latest?offerId=${o.id}`)));setTasks(Object.fromEntries(latest.filter(Boolean).map(t=>[t!.offerId,t!]))) }catch(e){setError(e instanceof Error?e.message:'Offer读取失败')}finally{setLoading(false)}},[]);
  useEffect(()=>{api('/api/v1/auth/csrf').then(()=>api<User>('/api/v1/auth/me')).then(setCurrentUser).catch(()=>setCurrentUser(null)).finally(()=>setAuthChecked(true))},[]);
  useEffect(()=>{if(!currentUser)return;const original=window.fetch.bind(window);window.fetch=(input,init={})=>{const csrf=decodeURIComponent(document.cookie.match(/(?:^|; )XSRF-TOKEN=([^;]*)/)?.[1]??'');const method=(init.method??'GET').toUpperCase();return original(input,{...init,credentials:'include',headers:{...(!['GET','HEAD','OPTIONS'].includes(method)&&csrf?{'X-XSRF-TOKEN':csrf}:{}),...(init.headers||{})}})};return()=>{window.fetch=original}},[currentUser]);
  useEffect(()=>{if(!currentUser)return;const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load,currentUser]);
  useEffect(()=>{if(!showAdd)return;const timer=window.setTimeout(()=>{setRegionLoading(true);api<Region[]>(`/api/v1/regions?q=${encodeURIComponent(form.city)}&limit=30`).then(setRegions).catch(()=>setRegions([])).finally(()=>setRegionLoading(false))},220);return()=>window.clearTimeout(timer)},[form.city,showAdd]);

  const rows=useMemo(()=>offers.map((o,i)=>{const task=tasks[o.id],r=task?.report,gross=r?.grossAnnualIncome??o.monthlySalary*o.salaryMonths+o.annualBonus,cash=r?.disposableAnnualIncome??Math.max(0,gross*.75-o.annualHousingCost);return{...o,task,report:r,color:colors[i%colors.length],total:gross/10000,cash:cash/10000,match:r?.jobMatchScore??0,growth:r?.growthScore??0,stability:r?.stabilityScore??0}}),[offers,tasks]);
  const ranked=useMemo(()=>rows.map(o=>({...o,score:o.report?Math.round(Math.min(100,o.cash*3.5)*income/100+o.growth*growth/100+o.match*Math.max(0,100-income-growth)/100):0})).sort((a,b)=>b.score-a.score),[rows,income,growth]);
  const selected=rows.find(x=>x.id===selectedId)??ranked[0]??null,recommended=ranked.find(x=>x.report)??null;

  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const body={company:form.company.trim(),role:form.role.trim(),city:form.city,monthlySalary:+form.monthlySalary,salaryMonths:+form.salaryMonths,annualBonus:+form.annualBonus,annualHousingCost:+form.annualHousingCost,jobDescription:form.jobDescription.trim()};const created=await api<Offer>('/api/v1/offers',{method:'POST',body:JSON.stringify(body)});setOffers(old=>[...old,created]);setSelectedId(created.id);setForm(blank);setShowAdd(false);await analyze(created.id);flash('Offer 已写入数据库，后端正在分析')}catch(e){setError(e instanceof Error?e.message:'提交失败')}finally{setBusy(false)}}
  async function parseOfferFile(file?:File){if(!file)return;setOfferFileBusy(true);setError('');try{const body=new FormData();body.append('file',file);const response=await fetch('/api/v1/offers/file-preview',{method:'POST',body});if(!response.ok)throw new Error(await response.text());const parsed=await response.json() as {company?:string;role?:string;city?:string;content?:string;filename:string};setForm(old=>({...old,company:parsed.company||old.company,role:parsed.role||old.role,city:parsed.city||old.city,jobDescription:parsed.content||old.jobDescription}));setShowAdd(true);flash(`已识别 ${parsed.filename}，请确认自动填写的字段`)}catch(e){setError(e instanceof Error?e.message:'Offer 文件识别失败')}finally{setOfferFileBusy(false)}}
  async function remove(id:string){if(!confirm('确定删除这个 Offer 吗？数据库记录也会被删除。'))return;try{await api<void>(`/api/v1/offers/${id}`,{method:'DELETE'});setOffers(old=>old.filter(x=>x.id!==id));setTasks(old=>{const next={...old};delete next[id];return next});setSelectedId(null);flash('Offer 已从数据库删除')}catch(e){setError(e instanceof Error?e.message:'删除失败')}}
  async function seed(){setBusy(true);const examples=[{company:'星云科技',role:'Java 后端工程师',city:'北京',monthlySalary:22000,salaryMonths:14,annualBonus:30000,annualHousingCost:72000,jobDescription:'Java、Spring Boot、Redis、高并发订单系统'},{company:'云栖网络',role:'AI 全栈工程师',city:'杭州',monthlySalary:21000,salaryMonths:13,annualBonus:25000,annualHousingCost:48000,jobDescription:'Spring AI、RAG、React、Java Agent应用开发'},{company:'深海数据',role:'平台研发工程师',city:'深圳',monthlySalary:24000,salaryMonths:14,annualBonus:35000,annualHousingCost:66000,jobDescription:'Java、Spring Cloud、数据平台与微服务治理'}];try{const made:Offer[]=[];for(const item of examples)made.push(await api<Offer>('/api/v1/offers',{method:'POST',body:JSON.stringify(item)}));setOffers(old=>[...old,...made]);setSelectedId(made[0].id);for(const item of made)await analyze(item.id);flash('3条示例已真实写入数据库')}catch(e){setError(e instanceof Error?e.message:'导入失败')}finally{setBusy(false)}}

  async function authenticate(e:FormEvent){e.preventDefault();setAuthBusy(true);setAuthError('');try{await api('/api/v1/auth/csrf');const user=await api<User>(`/api/v1/auth/${authMode}`,{method:'POST',body:JSON.stringify(credentials)});localStorage.removeItem('offerpilot.conversationId');setCurrentUser(user)}catch(e){setAuthError(e instanceof Error?e.message:'认证失败')}finally{setAuthBusy(false)}}
  async function logout(){try{await api<void>('/api/v1/auth/logout',{method:'POST'})}finally{localStorage.removeItem('offerpilot.conversationId');setCurrentUser(null);setFollowUp('');setOffers([]);setTasks({});setCredentials({username:'',displayName:'',password:''});void api('/api/v1/auth/csrf')}}
  if(!authChecked)return <main className="auth-page"><div className="loader"/></main>;
  if(!currentUser)return <main className="auth-page"><form className="auth-card" onSubmit={authenticate}><div className="brand"><span className="brand-mark">O</span><span>OfferPilot</span></div><span className="eyebrow">SECURE DECISION WORKSPACE</span><h1>{authMode==='login'?'登录账号':'注册账号'}</h1><p>{authMode==='login'?'登录后读取属于你的长期记忆。':'密码使用 BCrypt 哈希保存，不存储明文。'}</p><label>用户名<input required minLength={3} value={credentials.username} onChange={e=>setCredentials({...credentials,username:e.target.value})} placeholder="3-30位字母、数字或下划线"/></label>{authMode==='register'&&<label>显示名称<input required value={credentials.displayName} onChange={e=>setCredentials({...credentials,displayName:e.target.value})} placeholder="例如：陈同学"/></label>}<label>密码<input required minLength={8} type="password" value={credentials.password} onChange={e=>setCredentials({...credentials,password:e.target.value})} placeholder="至少8位"/></label>{authError&&<div className="auth-error">{authError}</div>}<button className="auth-submit" disabled={authBusy}>{authBusy?'请稍候…':authMode==='login'?'登录':'注册并登录'}</button><button type="button" className="auth-switch" onClick={()=>{setAuthMode(authMode==='login'?'register':'login');setAuthError('')}}>{authMode==='login'?'没有账号？立即注册':'已有账号？返回登录'}</button></form></main>;
  return <main className="app-shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">O</span><span>OfferPilot</span></div><nav><button onClick={()=>setActive('dashboard')} className={`nav-item ${active==='dashboard'?'active':''}`}><span>⌁</span> 决策工作台</button><button onClick={()=>setActive('offers')} className={`nav-item ${active==='offers'?'active':''}`}><span>▤</span> 我的 Offer <b>{offers.length}</b></button><button onClick={()=>setActive('history')} className={`nav-item ${active==='history'?'active':''}`}><span>⌕</span> 分析记录</button><button onClick={()=>setActive('resume')} className={`nav-item ${active==='resume'?'active':''}`}><span>▦</span> 我的简历</button><button onClick={()=>setActive('chat')} className={`nav-item ${active==='chat'?'active':''}`}><span>✦</span> 顾问问答</button></nav><div className="backend-state"><i/> AI 顾问 · 已连接<small>实时检索 / 知识库 / 数据计算</small></div><div className="side-foot"><div className="avatar">{currentUser.displayName.slice(0,1)}</div><div><strong>{currentUser.displayName}</strong><small>@{currentUser.username}</small></div><button onClick={logout}>退出</button></div></aside>
    <section className="workspace">
      {active==='resume'?<ResumeView key={currentUser.id}/>:active!=='dashboard'?<SecondaryViews initialQuestion={followUp} view={active} offers={offers} onOpenOffer={id=>{setSelectedId(id);setActive('dashboard')}}/>:<>
      <header className="topbar"><div><p>你好，{currentUser.displayName}</p><h1>你的秋招决策工作台</h1></div><div className="top-actions"><button className="ghost" onClick={()=>{navigator.clipboard?.writeText(location.href);flash('报告链接已复制')}}>分享报告</button><label className={`offer-upload ${offerFileBusy?'disabled':''}`}>{offerFileBusy?'识别中…':'⇧ 上传 Offer'}<input type="file" accept=".pdf,.docx,.txt,.md,.markdown,.csv" disabled={offerFileBusy} onChange={e=>void parseOfferFile(e.target.files?.[0])}/></label><button className="primary" onClick={()=>setShowAdd(true)}>＋ 添加 Offer</button></div></header>
      {error&&<div className="error-banner"><span>!</span><b>后端请求失败</b><p>{error}</p><button onClick={()=>setError('')}>关闭</button></div>}
      <div className="insight-banner"><div className="ai-orb">✦</div><div><span>真实后端决策摘要</span><h2>{recommended?`${recommended.company} 在当前权重下领先`:'添加 Offer 后生成真实分析'}</h2><p>{recommended?.report?.recommendation??'数据会写入 PostgreSQL，Redis 跟踪异步任务，Java引擎完成薪税测算。'}</p></div><button disabled={!recommended} onClick={()=>{setSelectedId(recommended?.id??null);setShowReport(true)}}>查看完整依据 <span>→</span></button></div>
      <div className="section-heading"><div><h2>Offer 横向对比</h2><p>来自 Spring Boot API · 金额单位：万元/年</p></div><div className="segmented">{(['综合视图','收入视图'] as const).map(x=><button key={x} onClick={()=>setView(x)} className={view===x?'on':''}>{x}</button>)}</div></div>
      {loading?<div className="empty-state"><div className="loader"/><h3>正在读取后端数据</h3></div>:offers.length===0?<div className="empty-state"><span>◎</span><h3>数据库里还没有 Offer</h3><p>录入自己的Offer，或导入示例验证完整链路。</p><div><button onClick={()=>setShowAdd(true)}>添加真实 Offer</button><button className="secondary" disabled={busy} onClick={seed}>{busy?'正在写入…':'导入演示数据'}</button></div></div>:<div className="offer-grid">{rows.map(o=><article key={o.id} onClick={()=>setSelectedId(o.id)} className={`offer-card ${selectedId===o.id?'selected':''}`}><div className="offer-top"><span className="company-logo" style={{background:o.color}}>{o.company[0]}</span><div><h3>{o.company}</h3><p>{o.role} · {o.city}</p></div>{recommended?.id===o.id&&<em>当前推荐</em>}</div><div className="salary"><strong>{o.total.toFixed(1)}</strong><span>万<br/>预计总包</span></div><div className="metric-row"><span>可支配收入 <b>{o.report?`${o.cash.toFixed(1)} 万`:'分析后可见'}</b></span><span>{view==='综合视图'?'岗位匹配':'住房支出'} <b>{view==='综合视图'?(o.report?`${o.match}%`:'—'):`${(o.annualHousingCost/10000).toFixed(1)} 万`}</b></span></div><div className="progress"><i style={{width:`${o.task?.progress??0}%`,background:o.color}}/></div><div className={`task-state ${o.task?.status==='FAILED'?'failed':''}`}><span>{status[o.task?.status??'']??'尚未分析'}</span><b>{o.task?.progress??0}%</b></div><div className="card-actions"><button onClick={e=>{e.stopPropagation();void analyze(o.id)}}>重新分析</button><button onClick={e=>{e.stopPropagation();void remove(o.id)}}>删除</button></div></article>)}</div>}
      <DecisionWorkbench key={currentUser.id} offers={offers} tasks={tasks} onAsk={q=>{setFollowUp(q);setActive('chat')}}/>
      <div className="scenario-bar"><div><b>情景模拟</b><span>一键切换决策侧重</span></div>{['均衡决策','收入优先','成长优先','稳定优先'].map(x=><button key={x} className={scenario===x?'active':''} onClick={()=>{setScenario(x);if(x==='收入优先'){setIncome(55);setGrowth(20)}else if(x==='成长优先'){setIncome(20);setGrowth(55)}else if(x==='稳定优先'){setIncome(25);setGrowth(25)}else{setIncome(40);setGrowth(35)}}}>{x}</button>)}<button className="agent-run" disabled={!selected?.task} onClick={()=>setShowAgent(true)}>✦ 查看 Agent 轨迹</button></div>
      <div className="lower-grid"><section className="panel preferences"><div className="panel-title"><div><h2>临时排名试算</h2><p>仅供当前页面试算，不覆盖上方已保存的个人偏好</p></div><span>前端实时计算</span></div><label><span>收入与生活成本 <b>{income}%</b></span><input type="range" min="15" max="55" value={income} onChange={e=>setIncome(+e.target.value)}/></label><label><span>技术成长空间 <b>{growth}%</b></span><input type="range" min="15" max="55" value={growth} onChange={e=>setGrowth(+e.target.value)}/></label><div className="weight-note"><span>i</span>薪税由Java后端计算，权重排名在页面实时更新</div></section><section className="panel ranking"><div className="panel-title"><div><h2>实时推荐排名</h2><p>已完成分析的Offer才有有效分数</p></div><button onClick={load}>刷新数据</button></div>{ranked.length?ranked.map((o,i)=><div className="rank-row" key={o.id}><strong>{i+1}</strong><span className="mini-logo" style={{background:o.color}}>{o.company[0]}</span><div><b>{o.company}</b><small>{o.city} · {o.role}</small></div><em>{o.score}<small>综合分</small></em></div>):<p className="muted-center">等待Offer数据</p>}</section></div>
      </>}
    </section>
    {showAgent&&selected&&<div className="drawer-backdrop" onClick={()=>setShowAgent(false)}><aside className="agent-drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setShowAgent(false)}>×</button><span className="eyebrow">求职分析过程</span><h2>真实 Agent 轨迹</h2><p className="drawer-intro">任务：{selected.task?.id??'尚未创建'} · {status[selected.task?.status??'']??'未知'}</p>{[['01','Offer写入数据库','PostgreSQL持久化薪资与岗位信息'],['02','执行确定性计算','Java薪税引擎计算收入、社保个税'],['03','缓存任务状态','Redis记录异步任务进度'],['04','RAG语义检索','Qwen Embedding + pgvector HNSW召回政策切片'],['05','Qwen证据推理','Spring AI组装上下文并输出带来源结论']].map((s,i)=><div className="agent-step" key={s[0]}><i>{s[0]}</i><div><b>{s[1]}</b><p>{s[2]}</p></div><em>{(selected.task?.progress??0)>=(i+1)*20?'✓ 完成':'等待'}</em></div>)}<div className="evidence-box"><b>后端状态：{status[selected.task?.status??'']??'尚未分析'}</b><span>公共政策资料由后台维护，问答会提供参考来源。</span></div></aside></div>}
    {showAdd&&<div className="modal-backdrop" onClick={()=>!busy&&setShowAdd(false)}><form className="modal" onSubmit={submit} onClick={e=>e.stopPropagation()}><button type="button" className="close" onClick={()=>setShowAdd(false)}>×</button><span className="eyebrow">DATABASE-BACKED OFFER</span><h2>添加一个真实 Offer</h2><p>提交后写入PostgreSQL，并创建异步分析任务。</p><fieldset><legend>1 · 基本信息</legend><label>公司与岗位<div className="field-row"><input required value={form.company} onChange={e=>setForm({...form,company:e.target.value})} placeholder="公司名称"/><input required value={form.role} onChange={e=>setForm({...form,role:e.target.value})} placeholder="岗位名称"/></div></label><label>工作城市<div className="region-picker"><input required autoComplete="off" value={form.city} onChange={e=>setForm({...form,city:e.target.value})} placeholder="输入城市、自治州或地区名称"/>{regionLoading&&<i>查询中…</i>}{form.city&&regions.length>0&&<div>{regions.map(r=><button type="button" key={r.code} onClick={()=>{setForm({...form,city:r.city});setRegions([])}}><b>{r.city}</b><span>{r.province} · 区划基准 {r.baselineYear}</span></button>)}</div>}</div></label></fieldset><fieldset><legend>2 · 薪酬与住房</legend><div className="field-row"><label>月薪（元）<input required min="1" type="number" value={form.monthlySalary} onChange={e=>setForm({...form,monthlySalary:e.target.value})}/></label><label>薪资月数<input required min="12" max="24" step="0.5" type="number" value={form.salaryMonths} onChange={e=>setForm({...form,salaryMonths:e.target.value})}/></label></div><div className="field-row"><label>年度奖金（元）<input required min="0" type="number" value={form.annualBonus} onChange={e=>setForm({...form,annualBonus:e.target.value})}/></label><label>年度住房支出（元）<input required min="0" type="number" value={form.annualHousingCost} onChange={e=>setForm({...form,annualHousingCost:e.target.value})}/></label></div></fieldset><details><summary>3 · 岗位说明（可选）</summary><label>Offer / JD内容<textarea value={form.jobDescription} onChange={e=>setForm({...form,jobDescription:e.target.value})} placeholder="粘贴技术栈、岗位职责和任职要求…"/></label></details><p>工时、通勤与福利可在保存后的“决策对比”中补充，未知信息可留空。</p><button disabled={busy} className="modal-primary">{busy?'正在保存并创建任务…':'保存并开始后端分析 →'}</button></form></div>}
    {showReport&&selected?.report&&<div className="modal-backdrop" onClick={()=>setShowReport(false)}><section className="modal report" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setShowReport(false)}>×</button><span className="eyebrow">BACKEND DECISION REPORT</span><h2>{selected.company} 分析报告</h2><div className="report-score"><strong>{ranked.find(x=>x.id===selected.id)?.score??0}</strong><span>当前权重综合分<br/><b>置信度 {selected.report.confidence}%</b></span></div><h3>后端结论</h3><p className="report-copy">{selected.report.recommendation}</p><h3>优势与风险</h3><ul>{selected.report.strengths.map(x=><li key={x}><b>优势：</b>{x}</li>)}{selected.report.risks.map(x=><li key={x}><b>风险：</b>{x}</li>)}</ul><h3>结论依据</h3>{selected.report.evidence.map(x=><div className="source" key={x.title}><span>{x.title}</span><b>{x.source} · {x.effectiveDate}</b></div>)}<button className="modal-primary" onClick={()=>setShowReport(false)}>我知道了</button></section></div>}
    {toast&&<div className="toast">✓ {toast}</div>}
  </main>
}
