'use client';
import {FormEvent,useEffect,useState} from 'react';
import './stream.css';
type Offer={id:string;company:string;role:string;city:string;monthlySalary:number;salaryMonths:number;annualBonus:number};
type Source={title:string;url:string;publishedAt?:string;level?:string;siteName?:string;city?:string;similarity?:number;retrievalMode?:string;vectorRank?:number;keywordRank?:number;keywordScore?:number;rrfScore?:number;sectionTitle?:string;effectiveDate?:string;expiryDate?:string};
type City={city:string;socialBase:string;socialNote:string;newHomePriceIndex:number;housingNote:string;sources:Source[]};
type Trace={embeddingMs:number;vectorSearchMs:number;llmMs:number;retrievedChunks:number;embeddingModel:string;index:string;totalMs:number};
type SkillCall={name:string;input:string;output:string;status:string;durationMs:number;cacheHit:boolean};
type RetrievalTrace={strategy:string;embeddingMs:number;vectorSearchMs:number;keywordSearchMs:number;fusionMs:number;totalMs:number;vectorCandidates:number;keywordCandidates:number;hitCount:number};
type Message={role:'user'|'assistant';text:string;sources?:Source[];mode?:string;trace?:Trace;retrieval?:RetrievalTrace;skillCalls?:SkillCall[];totalMs?:number;runId?:string;stage?:string};
async function request<T>(url:string,init?:RequestInit):Promise<T>{const csrf=decodeURIComponent(document.cookie.match(/(?:^|; )XSRF-TOKEN=([^;]*)/)?.[1]??'');const method=(init?.method??'GET').toUpperCase();const r=await fetch(url,{...init,credentials:'include',headers:{'Content-Type':'application/json',...(!['GET','HEAD','OPTIONS'].includes(method)&&csrf?{'X-XSRF-TOKEN':csrf}:{}),...(init?.headers||{})}});if(!r.ok)throw new Error(await r.text());return r.status===204?undefined as T:r.json()}

export default function SecondaryViews({view,offers,onOpenOffer,initialQuestion=''}:{initialQuestion?:string;view:'offers'|'cities'|'chat';offers:Offer[];onOpenOffer:(id:string)=>void}){
 const [cities,setCities]=useState<City[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [question,setQuestion]=useState(initialQuestion),[offerId,setOfferId]=useState(initialQuestion?'':offers[0]?.id??''),[sending,setSending]=useState(false);
 const [messages,setMessages]=useState<Message[]>([{role:'assistant',text:'我是 OfferPilot 求职助手，可以帮你修改简历、准备面试、匹配岗位和比较 Offer，也可以查询与求职相关的政策资料。'}]);
 const load=()=>{setLoading(true);setError('');request<City[]>('/api/v1/cities').then(setCities).catch(e=>setError(e.message||'数据读取失败')).finally(()=>setLoading(false))};
 useEffect(()=>{const timer=window.setTimeout(load,0);return()=>window.clearTimeout(timer)},[]);
 async function ask(e:FormEvent){e.preventDefault();if(!question.trim())return;const q=question.trim();const conversationId=localStorage.getItem('offerpilot.conversationId');const userId=localStorage.getItem('offerpilot.userId')||'local-user';setMessages(x=>[...x,{role:'user',text:q},{role:'assistant',text:'',stage:'正在连接决策服务'}]);setQuestion('');setSending(true);const patchLast=(patch:Partial<Message>)=>setMessages(x=>{const next=[...x],last=next.length-1;next[last]={...next[last],...patch};return next});try{const response=await fetch('/api/v1/chat/stream',{method:'POST',headers:{'Content-Type':'application/json','Accept':'text/event-stream'},body:JSON.stringify({question:q,offerId:offerId||null,conversationId,userId})});if(!response.ok||!response.body)throw new Error(await response.text());const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const blocks=buffer.split(/\r?\n\r?\n/);buffer=blocks.pop()??'';for(const block of blocks){const event=block.split(/\r?\n/).find(x=>x.startsWith('event:'))?.slice(6).trim();const raw=block.split(/\r?\n/).filter(x=>x.startsWith('data:')).map(x=>x.slice(5).trim()).join('\n');if(!raw)continue;const data=JSON.parse(raw);if(event==='meta'){patchLast({runId:data.runId});if(data.conversationId)localStorage.setItem('offerpilot.conversationId',data.conversationId)}if(event==='status')patchLast({stage:data.message});if(event==='sources')patchLast({sources:data.sources??[]});if(event==='skills')patchLast({skillCalls:data.skillCalls??[]});if(event==='token')setMessages(x=>{const next=[...x],last=next.length-1;next[last]={...next[last],text:next[last].text+(data.token??''),stage:undefined};return next});if(event==='done')patchLast({totalMs:data.totalMs,mode:data.mode,stage:undefined});if(event==='error')throw new Error(data.message??'生成失败')}}}catch(e){patchLast({text:`请求失败：${e instanceof Error?e.message:'未知错误'}`,stage:undefined})}finally{setSending(false)}}
 if(loading)return <div className="view-loading"><div className="loader"/><p>正在加载数据…</p></div>;
 const title=view==='offers'?'我的 Offer':view==='cities'?'城市数据':'Offer 顾问';
 return <div className="secondary-view"><header className="view-header"><div><p>OfferPilot 求职工作区</p><h1>{title}</h1></div><span className="live-pill">● 服务正常</span></header>{error&&<div className="error-banner"><b>请求失败</b><p>{error}</p></div>}
 {view==='offers'&&<><div className="view-summary"><b>{offers.length}</b><span>数据库中的Offer<br/><small>刷新页面仍会保留</small></span></div><div className="manage-list">{offers.map(o=><article key={o.id}><div className="company-logo">{o.company[0]}</div><div><h3>{o.company}</h3><p>{o.role} · {o.city}</p></div><span>¥{o.monthlySalary.toLocaleString()} × {o.salaryMonths}薪</span><button onClick={()=>onOpenOffer(o.id)}>回到工作台分析 →</button></article>)}</div></>}
 {view==='cities'&&<><div className="city-grid">{cities.map(c=><article className="city-card" key={c.city}><span>官方资料</span><h2>{c.city}</h2><div><small>社保缴费口径</small><b>{c.socialBase}</b><p>{c.socialNote}</p></div><div><small>新房价格同比指数</small><b>{c.newHomePriceIndex}</b><p>{c.housingNote}（上年同月=100）</p></div></article>)}</div><section className="sources-panel"><h2>数据来源与使用说明</h2><p>指标来自政府部门或国家统计局，页面用于Offer比较，不替代经办机构确认。</p>{cities.flatMap(c=>c.sources.map(s=>({...s,city:c.city}))).filter((s,i,a)=>a.findIndex(x=>x.url===s.url)===i).map(s=><a href={s.url} target="_blank" rel="noreferrer" key={s.url}><b>{s.city} · {s.title}</b><span>{s.level} · {s.publishedAt} ↗</span></a>)}</section></>}
 {view==='chat'&&<div className="chat-layout"><section className="chat-panel"><div className="chat-context"><label>关联 Offer<select value={offerId} onChange={e=>setOfferId(e.target.value)}><option value="">不关联具体 Offer</option>{offers.map(o=><option value={o.id} key={o.id}>{o.company} · {o.role}</option>)}</select></label><span>个人资料 · 决策偏好 · Offer 信息</span></div><div className="messages">{messages.map((m,i)=><div className={`message ${m.role}`} key={i}><b>{m.role==='user'?'你':'OfferPilot 求职助手'}</b>{m.stage&&<div className="answer-stage"><i/>{m.stage}</div>}<p>{m.text}{m.role==='assistant'&&sending&&i===messages.length-1&&<i className="stream-cursor"/>}</p>{m.sources&&m.sources.length>0&&<div className="answer-sources"><strong>参考来源 · {m.sources.length}</strong><div>{m.sources.map((s,n)=><a href={s.url} target="_blank" rel="noreferrer" key={`${s.url}-${n}`}><span>{n+1}</span><div><b>{s.title||s.siteName||'公开资料'}</b><small>{[s.siteName,s.city,s.sectionTitle,s.effectiveDate?`${s.effectiveDate} 起生效`:null,s.expiryDate?`${s.expiryDate} 失效`:null,s.publishedAt].filter(Boolean).join(' · ')||s.url.replace(/^https?:\/\/([^/]+).*$/,'$1')}</small></div><em>↗</em></a>)}</div></div>}{m.totalMs!=null&&<div className="answer-meta"><span>已核验 {m.sources?.length??0} 个来源</span><span>{(m.totalMs/1000).toFixed(1)} 秒</span></div>}</div>)}</div><form className="chat-input" onSubmit={ask}><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="例如：比较这几份 Offer，并结合我的经历给出建议"/><button disabled={sending}>{sending?'生成中…':'发送问题'}</button></form></section><aside className="question-tips"><h3>你可以这样问</h3>{['帮我检查简历中可以改进的表达','结合岗位要求判断我的匹配程度','比较几个 Offer 的收入与住房成本','列出下一轮沟通需要向 HR 确认的问题'].map(q=><button key={q} onClick={()=>setQuestion(q)}>{q}</button>)}<p>顾问会结合你的简历、Offer 信息和可信公开资料提供建议。关键决定请以政府部门和公司正式文件为准。</p></aside></div>}
 </div>
}
