'use client';
import {FormEvent,useEffect,useState} from 'react';
import './rag.css';
import './hybrid-rag.css';
import './stream.css';
import UrlKnowledgeImporter from './UrlKnowledgeImporter';
import FileKnowledgeImporter from './FileKnowledgeImporter';
type Offer={id:string;company:string;role:string;city:string;monthlySalary:number;salaryMonths:number;annualBonus:number};
type Task={id:string;offerId:string;status:string;progress:number;createdAt?:string};
type Source={title:string;url:string;publishedAt?:string;level?:string;siteName?:string;city?:string;similarity?:number;retrievalMode?:string;vectorRank?:number;keywordRank?:number;keywordScore?:number;rrfScore?:number;sectionTitle?:string;effectiveDate?:string;expiryDate?:string};
type City={city:string;socialBase:string;socialNote:string;newHomePriceIndex:number;housingNote:string;sources:Source[]};
type Doc={id:string;title:string;city?:string;sourceUrl:string;contentLength:number;chunkCount:number;parentCount:number;status:string;policyType?:string;effectiveDate?:string;expiryDate?:string;versionLabel?:string;authorityLevel:number;createdAt:string};
type Trace={embeddingMs:number;vectorSearchMs:number;llmMs:number;retrievedChunks:number;embeddingModel:string;index:string;totalMs:number};
type SkillCall={name:string;input:string;output:string;status:string;durationMs:number;cacheHit:boolean};
type RetrievalTrace={strategy:string;embeddingMs:number;vectorSearchMs:number;keywordSearchMs:number;fusionMs:number;totalMs:number;vectorCandidates:number;keywordCandidates:number;hitCount:number};
type Message={role:'user'|'assistant';text:string;sources?:Source[];mode?:string;trace?:Trace;retrieval?:RetrievalTrace;skillCalls?:SkillCall[];totalMs?:number;runId?:string;stage?:string};
const labels:Record<string,string>={COMPLETED:'分析完成',FAILED:'分析失败',QUEUED:'排队中',CALCULATING:'计算薪税',RETRIEVING:'检索依据',REASONING:'生成建议'};
async function request<T>(url:string,init?:RequestInit):Promise<T>{const csrf=decodeURIComponent(document.cookie.match(/(?:^|; )XSRF-TOKEN=([^;]*)/)?.[1]??'');const method=(init?.method??'GET').toUpperCase();const r=await fetch(url,{...init,credentials:'include',headers:{'Content-Type':'application/json',...(!['GET','HEAD','OPTIONS'].includes(method)&&csrf?{'X-XSRF-TOKEN':csrf}:{}),...(init?.headers||{})}});if(!r.ok)throw new Error(await r.text());return r.status===204?undefined as T:r.json()}

export default function SecondaryViews({view,offers,onOpenOffer,initialQuestion=''}:{initialQuestion?:string;view:'offers'|'cities'|'history'|'knowledge'|'chat';offers:Offer[];onOpenOffer:(id:string)=>void}){
 const [cities,setCities]=useState<City[]>([]),[history,setHistory]=useState<Task[]>([]),[docs,setDocs]=useState<Doc[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [question,setQuestion]=useState(initialQuestion),[offerId,setOfferId]=useState(initialQuestion?'':offers[0]?.id??''),[sending,setSending]=useState(false),[showIngest,setShowIngest]=useState(false);
 const [docForm,setDocForm]=useState({title:'',city:'',sourceUrl:'',content:'',policyType:'',effectiveDate:'',expiryDate:'',versionLabel:'',authorityLevel:2});
 const [messages,setMessages]=useState<Message[]>([{role:'assistant',text:'我是 OfferPilot 求职助手，可以帮你修改简历、准备面试、匹配岗位和比较 Offer，也可以查询与求职相关的政策资料。'}]);
 const load=()=>{setLoading(true);setError('');Promise.all([request<City[]>('/api/v1/cities'),request<Task[]>('/api/v1/analyses'),Promise.resolve([] as Doc[])]).then(([c,h,d])=>{setCities(c);setHistory(h);setDocs(d)}).catch(e=>setError(e.message||'数据读取失败')).finally(()=>setLoading(false))};
 useEffect(()=>{const timer=window.setTimeout(load,0);return()=>window.clearTimeout(timer)},[]);
 async function ask(e:FormEvent){e.preventDefault();if(!question.trim())return;const q=question.trim();const conversationId=localStorage.getItem('offerpilot.conversationId');const userId=localStorage.getItem('offerpilot.userId')||'local-user';setMessages(x=>[...x,{role:'user',text:q},{role:'assistant',text:'',stage:'正在连接决策服务'}]);setQuestion('');setSending(true);const patchLast=(patch:Partial<Message>)=>setMessages(x=>{const next=[...x],last=next.length-1;next[last]={...next[last],...patch};return next});try{const response=await fetch('/api/v1/chat/stream',{method:'POST',headers:{'Content-Type':'application/json','Accept':'text/event-stream'},body:JSON.stringify({question:q,offerId:offerId||null,conversationId,userId})});if(!response.ok||!response.body)throw new Error(await response.text());const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const blocks=buffer.split(/\r?\n\r?\n/);buffer=blocks.pop()??'';for(const block of blocks){const event=block.split(/\r?\n/).find(x=>x.startsWith('event:'))?.slice(6).trim();const raw=block.split(/\r?\n/).filter(x=>x.startsWith('data:')).map(x=>x.slice(5).trim()).join('\n');if(!raw)continue;const data=JSON.parse(raw);if(event==='meta'){patchLast({runId:data.runId});if(data.conversationId)localStorage.setItem('offerpilot.conversationId',data.conversationId)}if(event==='status')patchLast({stage:data.message});if(event==='sources')patchLast({sources:data.sources??[]});if(event==='skills')patchLast({skillCalls:data.skillCalls??[]});if(event==='token')setMessages(x=>{const next=[...x],last=next.length-1;next[last]={...next[last],text:next[last].text+(data.token??''),stage:undefined};return next});if(event==='done')patchLast({totalMs:data.totalMs,mode:data.mode,stage:undefined});if(event==='error')throw new Error(data.message??'生成失败')}}}catch(e){patchLast({text:`请求失败：${e instanceof Error?e.message:'未知错误'}`,stage:undefined})}finally{setSending(false)}}
 async function ingest(e:FormEvent){e.preventDefault();setSending(true);try{await request('/api/v1/knowledge',{method:'POST',body:JSON.stringify({...docForm,effectiveDate:docForm.effectiveDate||null,expiryDate:docForm.expiryDate||null})});setDocForm({title:'',city:'',sourceUrl:'',content:'',policyType:'',effectiveDate:'',expiryDate:'',versionLabel:'',authorityLevel:2});setShowIngest(false);load()}catch(e){setError(e instanceof Error?e.message:'知识导入失败')}finally{setSending(false)}}
 async function removeDoc(id:string){if(!confirm('删除该文档及其全部向量切片？'))return;await request(`/api/v1/knowledge/${id}`,{method:'DELETE'});setDocs(x=>x.filter(d=>d.id!==id))}
 const offerName=(id:string)=>offers.find(o=>o.id===id)?.company??'已删除Offer';
 if(loading)return <div className="view-loading"><div className="loader"/><p>正在读取后端数据…</p></div>;
 const title=view==='offers'?'我的 Offer':view==='cities'?'城市数据':view==='history'?'分析记录':view==='knowledge'?'RAG 知识库':'Offer顾问问答';
 return <div className="secondary-view"><header className="view-header"><div><p>OfferPilot 数据工作区</p><h1>{title}</h1></div><span className="live-pill">● 求职助手</span></header>{error&&<div className="error-banner"><b>请求失败</b><p>{error}</p></div>}{view==='knowledge'&&<><FileKnowledgeImporter onParsed={parsed=>{setDocForm(old=>({...old,title:old.title||parsed.suggestedTitle,sourceUrl:`upload://${encodeURIComponent(parsed.filename)}`,content:parsed.content}));setShowIngest(true)}}/><UrlKnowledgeImporter onDone={load}/></>}
 {view==='offers'&&<><div className="view-summary"><b>{offers.length}</b><span>数据库中的Offer<br/><small>刷新页面仍会保留</small></span></div><div className="manage-list">{offers.map(o=><article key={o.id}><div className="company-logo">{o.company[0]}</div><div><h3>{o.company}</h3><p>{o.role} · {o.city}</p></div><span>¥{o.monthlySalary.toLocaleString()} × {o.salaryMonths}薪</span><button onClick={()=>onOpenOffer(o.id)}>回到工作台分析 →</button></article>)}</div></>}
 {view==='cities'&&<><div className="city-grid">{cities.map(c=><article className="city-card" key={c.city}><span>官方资料</span><h2>{c.city}</h2><div><small>社保缴费口径</small><b>{c.socialBase}</b><p>{c.socialNote}</p></div><div><small>新房价格同比指数</small><b>{c.newHomePriceIndex}</b><p>{c.housingNote}（上年同月=100）</p></div></article>)}</div><section className="sources-panel"><h2>数据来源与使用说明</h2><p>指标来自政府部门或国家统计局，页面用于Offer比较，不替代经办机构确认。</p>{cities.flatMap(c=>c.sources.map(s=>({...s,city:c.city}))).filter((s,i,a)=>a.findIndex(x=>x.url===s.url)===i).map(s=><a href={s.url} target="_blank" rel="noreferrer" key={s.url}><b>{s.city} · {s.title}</b><span>{s.level} · {s.publishedAt} ↗</span></a>)}</section></>}
 {view==='history'&&<div className="history-list">{history.length?history.map(t=><article key={t.id}><i className={t.status==='COMPLETED'?'done':t.status==='FAILED'?'bad':''}/><div><h3>{offerName(t.offerId)}</h3><p>任务 {t.id.slice(0,8)} · {t.createdAt?new Date(t.createdAt).toLocaleString('zh-CN'):'时间未知'}</p></div><span><b>{labels[t.status]??t.status}</b><small>{t.progress}%</small></span></article>):<div className="empty-state"><h3>暂无分析记录</h3></div>}</div>}
 {view==='knowledge'&&<><section className="rag-hero"><div><span>HYBRID RAG PIPELINE</span><h2>可观察的混合检索知识库</h2><p>父子切片 → Qwen Embedding + PostgreSQL 关键词 → RRF 融合 → 有效期过滤</p></div><div><b>{docs.length}</b><small>文档</small><b>{docs.reduce((n,d)=>n+d.chunkCount,0)}</b><small>子切片</small></div><button onClick={()=>setShowIngest(true)}>＋ 导入知识</button></section><div className="doc-list">{docs.map(d=><article key={d.id}><div className="doc-icon">▦</div><div><h3>{d.title}</h3><a href={d.sourceUrl} target="_blank" rel="noreferrer">{d.sourceUrl}</a><p>{d.city||'通用'} · {d.policyType||'通用资料'} · {d.versionLabel||'未标版本'} · 有效期 {d.effectiveDate||'不限'} ～ {d.expiryDate||'长期'}</p></div><span><b>{d.chunkCount}</b> 个子切片<small>{d.parentCount||0} 个父块 · L{d.authorityLevel} · {d.status}</small></span><button onClick={()=>removeDoc(d.id)}>删除</button></article>)}{!docs.length&&<div className="empty-state"><h3>知识库为空</h3><p>导入官方政策或岗位资料，系统会自动进行父子切片、向量化和关键词索引。</p></div>}</div>{showIngest&&<div className="modal-backdrop"><form className="modal rag-form" onSubmit={ingest}><button type="button" className="close" onClick={()=>setShowIngest(false)}>×</button><span className="eyebrow">PARENT-CHILD + HYBRID RAG</span><h2>导入知识文档</h2><p>政策日期将用于自动排除未生效或已失效版本。</p><label>标题<input required value={docForm.title} onChange={e=>setDocForm({...docForm,title:e.target.value})}/></label><div className="field-row"><label>适用城市<input value={docForm.city} onChange={e=>setDocForm({...docForm,city:e.target.value})} placeholder="可留空"/></label><label>政策类型<input value={docForm.policyType} onChange={e=>setDocForm({...docForm,policyType:e.target.value})} placeholder="例如：社会保险"/></label></div><div className="field-row"><label>生效日期<input type="date" value={docForm.effectiveDate} onChange={e=>setDocForm({...docForm,effectiveDate:e.target.value})}/></label><label>失效日期<input type="date" value={docForm.expiryDate} onChange={e=>setDocForm({...docForm,expiryDate:e.target.value})}/></label></div><div className="field-row"><label>版本标识<input value={docForm.versionLabel} onChange={e=>setDocForm({...docForm,versionLabel:e.target.value})} placeholder="例如：2026版"/></label><label>权威等级<select value={docForm.authorityLevel} onChange={e=>setDocForm({...docForm,authorityLevel:Number(e.target.value)})}><option value={3}>L3 政府/公司正式文件</option><option value={2}>L2 权威机构</option><option value={1}>L1 一般资料</option><option value={0}>L0 未核验</option></select></label></div><label>原始来源URL<input required type="url" value={docForm.sourceUrl} onChange={e=>setDocForm({...docForm,sourceUrl:e.target.value})}/></label><label>文档正文<textarea required value={docForm.content} onChange={e=>setDocForm({...docForm,content:e.target.value})} placeholder="粘贴政策、岗位说明或行业报告正文…"/></label><button className="modal-primary" disabled={sending}>{sending?'正在建立混合索引…':'开始混合索引 →'}</button></form></div>}</>}
 {view==='chat'&&<div className="chat-layout"><section className="chat-panel"><div className="chat-context"><label>关联Offer<select value={offerId} onChange={e=>setOfferId(e.target.value)}><option value="">不关联具体Offer</option>{offers.map(o=><option value={o.id} key={o.id}>{o.company} · {o.role}</option>)}</select></label><span>实时资料 · 混合RAG · 长期记忆 · Offer数据</span></div><div className="messages">{messages.map((m,i)=><div className={`message ${m.role}`} key={i}><b>{m.role==='user'?'你':'OfferPilot 求职助手'}</b>{m.stage&&<div className="answer-stage"><i/>{m.stage}</div>}<p>{m.text}{m.role==='assistant'&&sending&&i===messages.length-1&&<i className="stream-cursor"/>}</p>{m.sources&&m.sources.length>0&&<div className="answer-sources"><strong>参考来源 · {m.sources.length}</strong><div>{m.sources.map((s,n)=><a href={s.url} target="_blank" rel="noreferrer" key={`${s.url}-${n}`}><span>{n+1}</span><div><b>{s.title||s.siteName||'公开资料'}</b><small>{[s.siteName,s.city,s.sectionTitle,s.retrievalMode,s.rrfScore!=null?`RRF ${s.rrfScore}`:null,s.effectiveDate?`${s.effectiveDate} 起生效`:null,s.expiryDate?`${s.expiryDate} 失效`:null,s.publishedAt].filter(Boolean).join(' · ')||s.url.replace(/^https?:\/\/([^/]+).*$/,'$1')}</small></div><em>↗</em></a>)}</div></div>}{m.skillCalls&&m.skillCalls.length>0&&<div className="rag-trace">{m.skillCalls.map((call,n)=><span key={`${call.name}-${n}`}>{call.name} · {call.durationMs}ms{call.cacheHit?' · 缓存':''}</span>)}</div>}{m.totalMs!=null&&<div className="answer-meta"><span>已核验 {m.sources?.length??0} 个来源</span><span>{(m.totalMs/1000).toFixed(1)} 秒</span></div>}</div>)}</div><form className="chat-input" onSubmit={ask}><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="例如：查询杭州最新社保政策，再结合这个Offer给出建议"/><button disabled={sending}>{sending?'生成中…':'发送问题'}</button></form></section><aside className="question-tips"><h3>你可以这样问</h3>{['查询这个城市最新社保政策并注明时间','结合知识库和JD判断技术成长空间','比较几个Offer的税后收入与住房成本','哪些结论有实时证据，哪些只是估算？'].map(q=><button key={q} onClick={()=>setQuestion(q)}>{q}</button>)}<p>回答可能使用实时公开资料、已导入知识库及你的Offer数据。关键决定请以政府部门和公司正式文件为准。</p></aside></div>}
 </div>
}
