'use client';
import {FormEvent,useEffect,useState} from 'react';
import './rag.css';
import './stream.css';
type Offer={id:string;company:string;role:string;city:string;monthlySalary:number;salaryMonths:number;annualBonus:number};
type Task={id:string;offerId:string;status:string;progress:number;createdAt?:string};
type Source={title:string;url:string;publishedAt?:string;level?:string;city?:string;similarity?:number};
type City={city:string;socialBase:string;socialNote:string;newHomePriceIndex:number;housingNote:string;sources:Source[]};
type Doc={id:string;title:string;city?:string;sourceUrl:string;contentLength:number;chunkCount:number;status:string;createdAt:string};
type Trace={embeddingMs:number;vectorSearchMs:number;llmMs:number;retrievedChunks:number;embeddingModel:string;index:string;totalMs:number};
type SkillCall={name:string;input:string;output:string;status:string;durationMs:number;cacheHit:boolean};
type Message={role:'user'|'assistant';text:string;sources?:Source[];mode?:string;trace?:Trace;skillCalls?:SkillCall[];totalMs?:number;runId?:string};
const labels:Record<string,string>={COMPLETED:'分析完成',FAILED:'分析失败',QUEUED:'排队中',CALCULATING:'计算薪税',RETRIEVING:'检索依据',REASONING:'生成建议'};
async function request<T>(url:string,init?:RequestInit):Promise<T>{const r=await fetch(url,{...init,headers:{'Content-Type':'application/json',...(init?.headers||{})}});if(!r.ok)throw new Error(await r.text());return r.status===204?undefined as T:r.json()}

export default function SecondaryViews({view,offers,onOpenOffer}:{view:'offers'|'cities'|'history'|'knowledge'|'chat';offers:Offer[];onOpenOffer:(id:string)=>void}){
 const [cities,setCities]=useState<City[]>([]),[history,setHistory]=useState<Task[]>([]),[docs,setDocs]=useState<Doc[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [question,setQuestion]=useState(''),[offerId,setOfferId]=useState(offers[0]?.id??''),[sending,setSending]=useState(false),[showIngest,setShowIngest]=useState(false);
 const [docForm,setDocForm]=useState({title:'',city:'',sourceUrl:'',content:''});
 const [messages,setMessages]=useState<Message[]>([{role:'assistant',text:'我是OfferPilot AI 顾问。你可以询问Offer比较、城市生活、社保政策、行业动态和岗位发展，我会按需查询实时资料与知识库。'}]);
 const load=()=>{setLoading(true);setError('');Promise.all([request<City[]>('/api/v1/cities'),request<Task[]>('/api/v1/analyses'),request<Doc[]>('/api/v1/knowledge')]).then(([c,h,d])=>{setCities(c);setHistory(h);setDocs(d)}).catch(e=>setError(e.message||'数据读取失败')).finally(()=>setLoading(false))};
 useEffect(load,[]);
 async function ask(e:FormEvent){e.preventDefault();if(!question.trim())return;const q=question.trim();setMessages(x=>[...x,{role:'user',text:q},{role:'assistant',text:''}]);setQuestion('');setSending(true);try{const response=await fetch('/api/v1/chat/stream',{method:'POST',headers:{'Content-Type':'application/json','Accept':'text/event-stream'},body:JSON.stringify({question:q,offerId:offerId||null})});if(!response.ok||!response.body)throw new Error(await response.text());const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const blocks=buffer.split(/\r?\n\r?\n/);buffer=blocks.pop()??'';for(const block of blocks){const event=block.split(/\r?\n/).find(x=>x.startsWith('event:'))?.slice(6).trim();const raw=block.split(/\r?\n/).filter(x=>x.startsWith('data:')).map(x=>x.slice(5).trim()).join('\n');if(!raw)continue;const data=JSON.parse(raw);if(event==='token')setMessages(x=>{const next=[...x],last=next.length-1;next[last]={...next[last],text:next[last].text+(data.token??'')};return next});if(event==='error')throw new Error(data.message??'生成失败')}}}catch(e){setMessages(x=>{const next=[...x],last=next.length-1;next[last]={role:'assistant',text:`请求失败：${e instanceof Error?e.message:'未知错误'}`};return next})}finally{setSending(false)}}
 async function ingest(e:FormEvent){e.preventDefault();setSending(true);try{await request('/api/v1/knowledge',{method:'POST',body:JSON.stringify(docForm)});setDocForm({title:'',city:'',sourceUrl:'',content:''});setShowIngest(false);load()}catch(e){setError(e instanceof Error?e.message:'知识导入失败')}finally{setSending(false)}}
 async function removeDoc(id:string){if(!confirm('删除该文档及其全部向量切片？'))return;await request(`/api/v1/knowledge/${id}`,{method:'DELETE'});setDocs(x=>x.filter(d=>d.id!==id))}
 const offerName=(id:string)=>offers.find(o=>o.id===id)?.company??'已删除Offer';
 if(loading)return <div className="view-loading"><div className="loader"/><p>正在读取后端数据…</p></div>;
 const title=view==='offers'?'我的 Offer':view==='cities'?'城市数据':view==='history'?'分析记录':view==='knowledge'?'RAG 知识库':'Offer顾问问答';
 return <div className="secondary-view"><header className="view-header"><div><p>OfferPilot 数据工作区</p><h1>{title}</h1></div><span className="live-pill">● Qwen · Spring AI · pgvector</span></header>{error&&<div className="error-banner"><b>请求失败</b><p>{error}</p></div>}
 {view==='offers'&&<><div className="view-summary"><b>{offers.length}</b><span>数据库中的Offer<br/><small>刷新页面仍会保留</small></span></div><div className="manage-list">{offers.map(o=><article key={o.id}><div className="company-logo">{o.company[0]}</div><div><h3>{o.company}</h3><p>{o.role} · {o.city}</p></div><span>¥{o.monthlySalary.toLocaleString()} × {o.salaryMonths}薪</span><button onClick={()=>onOpenOffer(o.id)}>回到工作台分析 →</button></article>)}</div></>}
 {view==='cities'&&<><div className="city-grid">{cities.map(c=><article className="city-card" key={c.city}><span>官方资料</span><h2>{c.city}</h2><div><small>社保缴费口径</small><b>{c.socialBase}</b><p>{c.socialNote}</p></div><div><small>新房价格同比指数</small><b>{c.newHomePriceIndex}</b><p>{c.housingNote}（上年同月=100）</p></div></article>)}</div><section className="sources-panel"><h2>数据来源与使用说明</h2><p>指标来自政府部门或国家统计局，页面用于Offer比较，不替代经办机构确认。</p>{cities.flatMap(c=>c.sources.map(s=>({...s,city:c.city}))).filter((s,i,a)=>a.findIndex(x=>x.url===s.url)===i).map(s=><a href={s.url} target="_blank" rel="noreferrer" key={s.url}><b>{s.city} · {s.title}</b><span>{s.level} · {s.publishedAt} ↗</span></a>)}</section></>}
 {view==='history'&&<div className="history-list">{history.length?history.map(t=><article key={t.id}><i className={t.status==='COMPLETED'?'done':t.status==='FAILED'?'bad':''}/><div><h3>{offerName(t.offerId)}</h3><p>任务 {t.id.slice(0,8)} · {t.createdAt?new Date(t.createdAt).toLocaleString('zh-CN'):'时间未知'}</p></div><span><b>{labels[t.status]??t.status}</b><small>{t.progress}%</small></span></article>):<div className="empty-state"><h3>暂无分析记录</h3></div>}</div>}
 {view==='knowledge'&&<><section className="rag-hero"><div><span>RAG PIPELINE</span><h2>可观察的向量知识库</h2><p>正文 → 900字符重叠切片 → Qwen text-embedding-v4（1024维）→ pgvector HNSW → 余弦相似度召回</p></div><div><b>{docs.length}</b><small>文档</small><b>{docs.reduce((n,d)=>n+d.chunkCount,0)}</b><small>切片</small></div><button onClick={()=>setShowIngest(true)}>＋ 导入知识</button></section><div className="doc-list">{docs.map(d=><article key={d.id}><div className="doc-icon">▦</div><div><h3>{d.title}</h3><a href={d.sourceUrl} target="_blank" rel="noreferrer">{d.sourceUrl}</a><p>{d.city||'通用'} · {d.contentLength.toLocaleString()}字符 · {new Date(d.createdAt).toLocaleString('zh-CN')}</p></div><span><b>{d.chunkCount}</b> 个向量切片<small>{d.status}</small></span><button onClick={()=>removeDoc(d.id)}>删除</button></article>)}{!docs.length&&<div className="empty-state"><h3>知识库为空</h3><p>导入官方政策或岗位资料，系统会自动切片并向量化。</p></div>}</div>{showIngest&&<div className="modal-backdrop"><form className="modal rag-form" onSubmit={ingest}><button type="button" className="close" onClick={()=>setShowIngest(false)}>×</button><span className="eyebrow">CHUNK + EMBEDDING + PGVECTOR</span><h2>导入知识文档</h2><p>建议粘贴政府官网正文，并填写原始URL。最多10万字符。</p><label>标题<input required value={docForm.title} onChange={e=>setDocForm({...docForm,title:e.target.value})}/></label><div className="field-row"><label>适用城市<input value={docForm.city} onChange={e=>setDocForm({...docForm,city:e.target.value})} placeholder="可留空"/></label><label>原始来源URL<input required type="url" value={docForm.sourceUrl} onChange={e=>setDocForm({...docForm,sourceUrl:e.target.value})}/></label></div><label>文档正文<textarea required value={docForm.content} onChange={e=>setDocForm({...docForm,content:e.target.value})} placeholder="粘贴政策、岗位说明或行业报告正文…"/></label><button className="modal-primary" disabled={sending}>{sending?'正在切片并生成向量…':'开始向量化入库 →'}</button></form></div>}</>}
 {view==='chat'&&<div className="chat-layout"><section className="chat-panel"><div className="chat-context"><label>关联Offer<select value={offerId} onChange={e=>setOfferId(e.target.value)}><option value="">不关联具体Offer</option>{offers.map(o=><option value={o.id} key={o.id}>{o.company} · {o.role}</option>)}</select></label><span>实时资料 · 个人知识库 · Offer数据</span></div><div className="messages">{messages.map((m,i)=><div className={`message ${m.role}`} key={i}><b>{m.role==='user'?'你':'OfferPilot AI 顾问'}</b><p>{m.text}{m.role==='assistant'&&sending&&i===messages.length-1&&<i className="stream-cursor"/>}</p></div>)}</div><form className="chat-input" onSubmit={ask}><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="例如：查询杭州最新社保政策，再结合这个Offer给出建议"/><button disabled={sending}>{sending?'生成中…':'发送问题'}</button></form></section><aside className="question-tips"><h3>你可以这样问</h3>{['查询这个城市最新社保政策并注明时间','结合知识库和JD判断技术成长空间','比较几个Offer的税后收入与住房成本','哪些结论有实时证据，哪些只是估算？'].map(q=><button key={q} onClick={()=>setQuestion(q)}>{q}</button>)}<p>回答可能使用实时公开资料、已导入知识库及你的Offer数据。关键决定请以政府部门和公司正式文件为准。</p></aside></div>}
 </div>
}
